#!/bin/sh

echo "Volaris OS initramfs starting..."

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo "Mounting tmpfs root at /mnt/runtime..."
mount -t tmpfs -o size=8G tmpfs /mnt/runtime


echo "Mounting base system (read-only) to hydrate RAM..."
mkdir -p /mnt/base
mount -t ext4 -o ro /dev/sda1 /mnt/base
echo "Copying base system into tmpfs..."
cp -a /mnt/base/* /mnt/runtime/
umount /mnt/base

echo "Switching to RAM-resident root..."
exec switch_root /mnt/runtime /sbin/init
